name: Check Stock

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Pull and run the prebuilt image
        run: | 
          docker run --rm \
          -e PINCODE=${{ secrets.PINCODE }} \
          -e TWILIO_SID=${{ secrets.TWILIO_SID }} \
          -e TWILIO_AUTH=${{ secrets.TWILIO_AUTH }} \
          -e TWILIO_FROM=${{ secrets.TWILIO_FROM }} \
          -e TWILIO_TO=${{ secrets.TWILIO_TO }} \
          ghcr.io/hiki-uwu/amul-bot:latest


